### ISSUE TITLE
Unable to load database "Please make sure that you are using the latest IP2Location BIN file"

### ISSUE THREAD

**Issue by pierre-roudaut-cko** [ip2location/ip2proxy-dotnet#4]
Hi,

I'm trying to perform a simple IP country lookup with the database product `PX3-IP-PROXYTYPE-COUNTRY-REGION-CITY.BIN` such as:

```c#
        var db = new IP2Location.Component();
        db.Open(@"C:\Users\PierreRoudaut\Downloads\IP2PROXY-IP-PROXYTYPE-COUNTRY-REGION-CITY.BIN", true);
        var result = db.IPQuery("50.201.95.250");
        Console.WriteLine(result.CountryShort);
```

But the following code throws an Exception with the message "Please make sure that you are using the latest IP2Location BIN file".
The database file is from 2022-04-26 downloaded with a trial license and is around ~210 MB.

After debugging the source code, I can see that the `LoadBIN()` asserts that the metadata.ProductCode isn't 1 (evaluated to 2 in this case).
```c#
              if (metaData.ProductCode != 1 && metaData.DBYear >= 21 || metaData.DBType == 80 && metaData.DBColumn == 75)
                throw new Exception("Incorrect IP2Location BIN file format. Please make sure that you are using the latest IP2Location BIN file.");
```
Could you please help me with this?

**Comment by ip2location-com** [comment]
The IP2Location .NET Component (https://github.com/ip2location/ip2location-dotnet/) is for reading IP2Location BIN files (https://www.ip2location.com/database/ip2location) while the IP2Proxy .NET Component (https://github.com/ip2location/ip2proxy-dotnet/) is for reading IP2Proxy BIN files (https://www.ip2location.com/database/ip2proxy).

If you just wish to lookup the country of a particular IP address, you need to get the DB1 BIN file and then query with your current code which is using the IP2Location .NET Component (https://www.nuget.org/packages/IP2Location.IPGeolocation).

On the other hand, if you wish to read proxy IP data, then you need to switch from the IP2Location .NET Component to the IP2Proxy .NET Component (https://www.nuget.org/packages/IP2Proxy).
