### ISSUE TITLE
Async version of methods

### ISSUE THREAD

**Issue by kristho91** [ip2location/ip2proxy-dotnet#5]
Hi,

Is there any plans for making async versions of the methods in this library?

**Comment by ip2location-com** [comment]
Hi,

We've added the async methods.

**Comment by kristho91** [comment]
Hi again,

I appreciate your efforts - but this is a blocking way to do it.

```
Public Function GetAllAsync(IP As String) As ProxyResult
    Return ProxyQueryAsync(IP).Result
End Function
```

should have been something like - without .Result, and returning a Task
Probably not quite correct - I'm no VB.NET dev (I write in C# normally)

```
Public Function GetAllAsync(IP As String) As Task(Of ProxyResult)
    Return ProxyQueryAsync(IP)
End Function
```

It seems like ProxyQueryAsync is implemented correctly but all helper methods calling it are doing the blocking.

**Comment by ip2location-com** [comment]
We've updated the codes. Please have another look.

**Comment by kristho91** [comment]
Way better! But you broke the output of most of the methods (except GetAllAsync).

Example:

![image](https://github.com/ip2location/ip2proxy-dotnet/assets/2781949/36a0f7ca-d00f-4d75-937e-86a532fbb80c)

This should be:

```
Public Async Function GetProviderAsync(IP As String) As Task(Of String)
    Return (Await ProxyQueryAsync(IP, Modes.PROVIDER)).Provider
End Function
```

This is the case for all methods returning a property of the ProxyResult

**Comment by ip2location-com** [comment]
Have made the changes. Please have another look.

**Comment by kristho91** [comment]
@ip2location That seems correct to me! :)
